### ISSUE TITLE
Deploy on Android

### ISSUE THREAD

**Issue by judithnaomi** [Cvalladares/gula_apong_mobile#32]

**Comment by Cvalladares** [comment]
At this moment, I have managed to install additional platforms to the Ionic project by defining:
ionic cordova platform add android
ionic resources

The project can be compiled by using:
ionic cordova prepare android
ionic cordova compile android

some limitations include that a specific JDK must be installed, an JDK 9.0 does not work.  THis must be verified first, and then added to the docmumentation

**Comment by Cvalladares** [comment]
- [ ] Must document dependencies for android deployment

**Comment by Cvalladares** [comment]
We have documented android deployment in the Readme.MD file from the repository.  When necessary to deploy, follow this guide, and find the APK  in the directory described in the project.  With regards to the signing of the application in order to deploy to the google play store,  an extra guide has been provided in the readme.md file.
